# Generated by Django 6.0.7 on 2026-07-11 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbbreviationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='abbreviation_tool.abbreviationcategory')),
            ],
            options={
                'verbose_name_plural': 'abbreviation categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AbbreviationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(db_index=True, max_length=100)),
                ('full_form', models.CharField(db_index=True, max_length=500)),
                ('normalized_abbreviation', models.CharField(db_index=True, editable=False, max_length=100)),
                ('normalized_full_form', models.CharField(db_index=True, editable=False, max_length=500)),
                ('service', models.CharField(blank=True, max_length=50)),
                ('context', models.TextField(blank=True)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('is_ambiguous', models.BooleanField(default=False)),
                ('is_preferred', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=10)),
                ('source_name', models.CharField(blank=True, max_length=150)),
                ('source_section', models.CharField(blank=True, max_length=150)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='abbreviation_tool.abbreviationcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_abbreviation_entries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_abbreviation_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('abbreviation', '-is_preferred', '-priority', 'full_form'),
                'permissions': [('access_abbreviation_tool', 'Can access DOCX Abbreviation Manager'), ('process_document', 'Can process DOCX documents'), ('search_dictionary', 'Can search abbreviation dictionary'), ('manage_dictionary', 'Can manage abbreviation dictionary'), ('import_dictionary', 'Can import abbreviation dictionary'), ('export_dictionary', 'Can export abbreviation dictionary'), ('manage_profiles', 'Can manage abbreviation profiles'), ('view_audit_log', 'Can view abbreviation audit log')],
            },
        ),
        migrations.CreateModel(
            name='AbbreviationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('abbreviation_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='abbreviation_tool.abbreviationentry')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='AbbreviationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='profiles', to='abbreviation_tool.abbreviationcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_abbreviation_profiles', to=settings.AUTH_USER_MODEL)),
                ('excluded_entries', models.ManyToManyField(blank=True, related_name='excluded_from_profiles', to='abbreviation_tool.abbreviationentry')),
                ('preferred_entries', models.ManyToManyField(blank=True, related_name='preferred_in_profiles', to='abbreviation_tool.abbreviationentry')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='abbreviationentry',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='entries', to='abbreviation_tool.abbreviationprofile'),
        ),
        migrations.CreateModel(
            name='AbbreviationVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=500)),
                ('normalized_variant', models.CharField(db_index=True, editable=False, max_length=500)),
                ('variant_type', models.CharField(choices=[('alternative_abbreviation', 'Alternative abbreviation'), ('alternative_full_form', 'Alternative full form'), ('plural', 'Plural'), ('possessive', 'Possessive'), ('hyphenated', 'Hyphenated'), ('legacy', 'Legacy'), ('service_specific', 'Service-specific'), ('spelling', 'Spelling variant')], max_length=30)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='abbreviation_tool.abbreviationentry')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentProcessingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('operation_type', models.CharField(choices=[('abbreviate', 'Abbreviate'), ('deabbreviate', 'Deabbreviate')], max_length=20)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('created', 'Created'), ('analysing', 'Analysing'), ('review', 'Review'), ('generating', 'Generating'), ('complete', 'Complete'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='created', max_length=20)),
                ('suggestion_count', models.PositiveIntegerField(default=0)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('ambiguous_count', models.PositiveIntegerField(default=0)),
                ('unsupported_element_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abbreviation_tool.abbreviationprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abbreviation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('abbreviate', 'Abbreviate'), ('deabbreviate', 'Deabbreviate')], max_length=20)),
                ('original_text', models.CharField(max_length=500)),
                ('proposed_text', models.CharField(max_length=500)),
                ('user_modified_text', models.CharField(blank=True, max_length=500)),
                ('container_type', models.CharField(max_length=30)),
                ('container_identifier', models.CharField(max_length=255)),
                ('paragraph_identifier', models.CharField(max_length=255)),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ambiguity_status', models.CharField(blank=True, max_length=30)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('ignored', 'Ignored')], default='pending', max_length=10)),
                ('mixed_format_warning', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abbreviation_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abbreviation_tool.abbreviationentry')),
                ('selected_meaning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_suggestions', to='abbreviation_tool.abbreviationentry')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='abbreviation_tool.documentprocessingsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='abbreviationentry',
            constraint=models.UniqueConstraint(fields=('normalized_abbreviation', 'normalized_full_form'), name='unique_normalized_abbreviation_pair'),
        ),
        migrations.AddConstraint(
            model_name='abbreviationvariant',
            constraint=models.UniqueConstraint(fields=('entry', 'normalized_variant', 'variant_type'), name='unique_abbreviation_variant'),
        ),
    ]
