# Generated by Django 6.0.7 on 2026-07-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbreviation_tool', '0002_import_jssdm_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentprocessingsession',
            name='processing_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentprocessingsession',
            name='replacement_policy',
            field=models.CharField(choices=[('all', 'Replace all eligible occurrences'), ('keep_first', 'Keep first occurrence in full'), ('define_first', 'Full form with abbreviation on first use')], default='define_first', max_length=20),
        ),
    ]
