# Generated by Django 6.0.7 on 2026-07-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abbreviation_tool', '0005_import_jssdm_ranks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abbreviationentry',
            options={'ordering': ('abbreviation', '-is_preferred', '-priority', 'full_form'), 'permissions': [('access_abbreviation_tool', 'Can access SD Checker'), ('process_document', 'Can process DOCX documents'), ('search_dictionary', 'Can search abbreviation dictionary'), ('manage_dictionary', 'Can manage abbreviation dictionary'), ('import_dictionary', 'Can import abbreviation dictionary'), ('export_dictionary', 'Can export abbreviation dictionary'), ('manage_profiles', 'Can manage abbreviation profiles'), ('view_audit_log', 'Can view abbreviation audit log')]},
        ),
    ]
