"""
Django settings for home_ai project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@13pmv_u_c-(#-cp)_r4g=0dknd#je0u(1n1#ad25zw*vkqg5i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'abbreviation_tool',
    'jssdm',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'home_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home_ai.context_processors.feature_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'home_ai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

DOCX_ABBREVIATION_TOOL_ENABLED = os.getenv("DOCX_ABBREVIATION_TOOL_ENABLED", "true").lower() in {"1", "true", "yes", "on"}
DOCX_ABBREVIATION_SESSION_TTL_MINUTES = int(os.getenv("DOCX_ABBREVIATION_SESSION_TTL_MINUTES", "30"))
DOCX_ABBREVIATION_TEMP_ROOT = os.getenv("DOCX_ABBREVIATION_TEMP_ROOT", str(BASE_DIR / ".private_docx_sessions"))
DOCX_ABBREVIATION_MAX_UNCOMPRESSED_MB = int(os.getenv("DOCX_ABBREVIATION_MAX_UNCOMPRESSED_MB", "250"))
DOCX_ABBREVIATION_MAX_ZIP_RATIO = int(os.getenv("DOCX_ABBREVIATION_MAX_ZIP_RATIO", "100"))
DOCX_ABBREVIATION_MAX_ZIP_MEMBERS = int(os.getenv("DOCX_ABBREVIATION_MAX_ZIP_MEMBERS", "5000"))
DOCX_ABBREVIATION_MAX_ACTIVE_SESSIONS = int(os.getenv("DOCX_ABBREVIATION_MAX_ACTIVE_SESSIONS", "5"))
DOCX_ABBREVIATION_MAX_SUGGESTIONS = int(os.getenv("DOCX_ABBREVIATION_MAX_SUGGESTIONS", "5000"))
DOCX_ABBREVIATION_ANALYSIS_TIMEOUT_SECONDS = int(os.getenv("DOCX_ABBREVIATION_ANALYSIS_TIMEOUT_SECONDS", "60"))
